import { 
  AssessmentResult, 
  calculateRoleReadiness, 
  Opportunity, 
  Application, 
  Certification,
  StudentProject,
  Achievement,
  StudentPortfolio,
  AdminStudentSummary,
  AdminVerificationItem,
  AdminAnalyticsData
} from '@skillbridge/shared';

// Realistic sample answers for Alex Rivera (Junior majoring in Computer Science)
export const SAMPLE_STUDENT_ANSWERS: Record<number, number> = {
  1: 4, // HTML/CSS - Proficient
  2: 4, // JavaScript - Proficient
  3: 4, // React - Proficient
  4: 3, // Git - Competent
  5: 3, // SQL - Competent
  6: 2, // Python - Beginner
  7: 4, // Communication - Proficient
  8: 4, // Teamwork - Proficient
  9: 4, // Problem Solving - Proficient
  10: 4 // Adaptability - Proficient
};

export function getSampleStudentAssessment(): AssessmentResult {
  const calc = calculateRoleReadiness(SAMPLE_STUDENT_ANSWERS);
  return {
    id: 'sample-assessment-alex-rivera',
    studentId: 'demo-student-id',
    totalScore: calc.totalScore,
    maxScore: calc.maxScore,
    percentage: calc.percentage,
    answers: SAMPLE_STUDENT_ANSWERS,
    skillScores: calc.skillScores,
    roleReadiness: calc.roleReadiness,
    recommendedRole: calc.recommendedRole,
    recommendationMessage: calc.recommendationMessage,
    completedAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
  };
}

export const SAMPLE_OPPORTUNITIES: Opportunity[] = [
  {
    id: 'opp-ind-1',
    recruiterId: 'demo-recruiter-id',
    title: 'Frontend React Engineering Intern',
    company: 'Nexus Cloud India',
    type: 'internship',
    workMode: 'hybrid',
    location: 'Bengaluru, Karnataka',
    stipendOrSalary: '₹45,000 / month',
    duration: '6 Months',
    deadline: '2026-10-25',
    description: 'Build responsive design systems, reactive web dashboards, and TypeScript microfrontends alongside senior engineers.',
    requiredSkills: ['React', 'TypeScript', 'HTML/CSS', 'Git'],
    eligibility: 'Current B.Tech / MCA 2026 or 2027 batch with 75%+ Frontend Role Readiness.',
    openingsCount: 6,
    status: 'active',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'opp-ind-2',
    recruiterId: 'rec-razorpay',
    title: 'Backend Systems & API Associate',
    company: 'Razorpay Payments',
    type: 'job',
    workMode: 'hybrid',
    location: 'Bengaluru, Karnataka',
    stipendOrSalary: '₹14,00,000 / year',
    duration: 'Full-Time',
    deadline: '2026-11-10',
    description: 'Engineer zero-downtime banking integration microservices, idempotency ledgers, and high-concurrency PostgreSQL transaction pipelines.',
    requiredSkills: ['SQL', 'Python', 'JavaScript', 'Git', 'Problem Solving'],
    eligibility: 'Final year engineering students with proven database and API modeling background.',
    openingsCount: 4,
    status: 'active',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'opp-ind-3',
    recruiterId: 'rec-zerodha',
    title: 'Web Platforms & UI Apprenticeship',
    company: 'Zerodha Broking',
    type: 'apprenticeship',
    workMode: 'remote',
    location: 'Remote (All India)',
    stipendOrSalary: '₹40,000 / month',
    duration: '12 Months',
    deadline: '2026-11-20',
    description: 'Join the trading terminal platform team to build sub-millisecond charting interfaces, WebSocket feeds, and accessible financial tools.',
    requiredSkills: ['JavaScript', 'HTML/CSS', 'React', 'Problem Solving'],
    eligibility: 'Passionate self-taught developers or engineering graduates with strong vanilla JavaScript foundations.',
    openingsCount: 3,
    status: 'active',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'opp-ind-4',
    recruiterId: 'rec-tcs',
    title: 'Data Intelligence & Analytics Specialist',
    company: 'TCS Innovation Labs',
    type: 'job',
    workMode: 'on_site',
    location: 'Hyderabad, Telangana',
    stipendOrSalary: '₹7,50,000 / year',
    duration: 'Full-Time',
    deadline: '2026-12-05',
    description: 'Transform client operational records into predictive machine learning models, executive dashboards, and statistical summaries.',
    requiredSkills: ['SQL', 'Python', 'Problem Solving', 'Communication'],
    eligibility: 'Graduates in Computer Science, Data Science, or Mathematics with 70%+ aggregate.',
    openingsCount: 10,
    status: 'active',
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'opp-ind-5',
    recruiterId: 'rec-infosys',
    title: 'Cloud Architecture & DevOps Workshop',
    company: 'Infosys Springboard',
    type: 'workshop',
    workMode: 'remote',
    location: 'Virtual / Online',
    stipendOrSalary: 'Free + ₹15,000 Merit Grant',
    duration: '4 Weeks',
    deadline: '2026-10-18',
    description: 'Intensive industry mentorship covering CI/CD automated deployment, container orchestration, and multi-cloud resilience.',
    requiredSkills: ['Git', 'Python', 'Adaptability'],
    eligibility: 'Open to all 2nd, 3rd, and 4th year college engineering students.',
    openingsCount: 50,
    status: 'active',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'opp-ind-6',
    recruiterId: 'rec-iitb',
    title: 'Faculty Development Program in AI & Systems',
    company: 'IIT Bombay / AICTE Collaboration',
    type: 'fdp',
    workMode: 'hybrid',
    location: 'Mumbai, Maharashtra',
    stipendOrSalary: 'Funded Research Grant (₹30,000)',
    duration: '2 Weeks',
    deadline: '2026-11-12',
    description: 'Upskill university engineering faculty and department chairs on modernizing academic curricula to reflect current industry demands.',
    requiredSkills: ['Python', 'SQL', 'Communication', 'Teamwork'],
    eligibility: 'Accredited university professors, assistant professors, and placement coordinators.',
    openingsCount: 25,
    status: 'active',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'opp-ind-7',
    recruiterId: 'rec-flipkart',
    title: 'SDE Intern — Catalog & Search Platforms',
    company: 'Flipkart Internet',
    type: 'internship',
    workMode: 'on_site',
    location: 'Bengaluru, Karnataka',
    stipendOrSalary: '₹85,000 / month',
    duration: '6 Months',
    deadline: '2026-10-31',
    description: 'Work on search indexing, real-time product recommendations, and distributed caching for millions of concurrent shoppers.',
    requiredSkills: ['JavaScript', 'React', 'SQL', 'Problem Solving', 'Git'],
    eligibility: 'Pre-final year engineering students with top-tier algorithmic problem solving.',
    openingsCount: 5,
    status: 'active',
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const SAMPLE_APPLICATIONS: Application[] = [
  {
    id: 'app-ind-1',
    opportunityId: 'opp-ind-1',
    opportunity: SAMPLE_OPPORTUNITIES[0], // Nexus Cloud India
    studentId: 'demo-student-id',
    studentName: 'Alex Rivera',
    studentEmail: 'alex.rivera@apex.edu',
    studentCollege: 'Apex Institute of Technology',
    studentRoleReadiness: 88,
    recruiterId: 'demo-recruiter-id',
    matchScore: 92,
    matchPercentage: 92,
    matchedSkills: ['React', 'TypeScript', 'HTML/CSS', 'Git'],
    missingSkills: [],
    recommendationMessage: 'You are a 92% match! You meet or exceed all industry requirements for this Frontend React Engineering Intern.',
    status: 'Shortlisted',
    appliedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    notes: 'Very excited about the distributed cloud console architecture at Nexus Cloud India.',
    recruiterNotes: 'Technical screening scheduled for Thursday 2:30 PM. Strong component design portfolio.',
    candidatePortfolio: {
      bio: 'Junior majoring in Computer Science with a focus on web application performance, TypeScript design systems, and responsive UX.',
      college: 'Apex Institute of Technology',
      degree: 'B.Tech Computer Science & Engineering',
      graduationYear: '2026',
      cgpaOrPercentage: '8.8 / 10 CGPA',
      roleReadinessScore: 88,
      recommendedRole: 'Frontend Developer',
      assessedSkills: {
        'React': 80,
        'JavaScript': 80,
        'HTML/CSS': 80,
        'Git': 60,
        'SQL': 60,
        'Problem Solving': 80,
      },
      projects: [
        {
          title: 'CampusPlacement Cloud Portal',
          description: 'Full-stack reactive placement matching dashboard with role readiness calculations.',
          tech: ['React', 'TypeScript', 'Tailwind CSS', 'Supabase'],
          githubUrl: 'https://github.com/alexrivera/campus-placement-portal',
        },
        {
          title: 'Algorithmic Trading Dashboard',
          description: 'Sub-millisecond WebSocket chart visualizer with responsive indicators.',
          tech: ['JavaScript', 'Canvas', 'HTML5', 'Node.js'],
          githubUrl: 'https://github.com/alexrivera/algo-charting',
        },
      ],
      certifications: [
        {
          id: 'cert-1',
          studentId: 'demo-student-id',
          title: 'Modern React Architecture & Component Design',
          issuer: 'Apex Institute of Technology — Department of CS',
          issueDate: '2026-05-20',
          credentialUrl: 'https://credentials.apex.edu/verify/CS-REACT-8821',
          status: 'Verified',
        },
      ],
    },
  },
  {
    id: 'app-ind-2',
    opportunityId: 'opp-ind-3',
    opportunity: SAMPLE_OPPORTUNITIES[2], // Zerodha Broking
    studentId: 'demo-student-id',
    studentName: 'Alex Rivera',
    studentEmail: 'alex.rivera@apex.edu',
    studentCollege: 'Apex Institute of Technology',
    studentRoleReadiness: 88,
    recruiterId: 'rec-zerodha',
    matchScore: 88,
    matchPercentage: 88,
    matchedSkills: ['JavaScript', 'HTML/CSS', 'React', 'Problem Solving'],
    missingSkills: [],
    recommendationMessage: 'You are an 88% match! Strong fit for high-performance trading platform frontends.',
    status: 'Interview',
    appliedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    notes: 'Passionate about sub-millisecond rendering and accessible financial software.',
    recruiterNotes: 'Round 1 technical discussion scheduled for Friday at 3:00 PM IST with UI Platform Leads.',
  },
  {
    id: 'app-ind-3',
    opportunityId: 'opp-ind-2',
    opportunity: SAMPLE_OPPORTUNITIES[1], // Razorpay Payments
    studentId: 'demo-student-id',
    studentName: 'Alex Rivera',
    studentEmail: 'alex.rivera@apex.edu',
    studentCollege: 'Apex Institute of Technology',
    studentRoleReadiness: 88,
    recruiterId: 'rec-razorpay',
    matchScore: 78,
    matchPercentage: 78,
    matchedSkills: ['JavaScript', 'Git', 'Problem Solving'],
    missingSkills: ['SQL Optimization', 'Python'],
    recommendationMessage: 'You are a 78% match. Improve SQL and Python to increase your interview eligibility.',
    status: 'Applied',
    appliedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    notes: 'Keen on high-scale payment processing and distributed consensus.',
    recruiterNotes: 'Application received and under initial batch screening.',
  },
  {
    id: 'app-ind-4',
    opportunityId: 'opp-ind-5',
    opportunity: SAMPLE_OPPORTUNITIES[4], // Infosys Springboard
    studentId: 'demo-student-id',
    studentName: 'Alex Rivera',
    studentEmail: 'alex.rivera@apex.edu',
    studentCollege: 'Apex Institute of Technology',
    studentRoleReadiness: 88,
    recruiterId: 'rec-infosys',
    matchScore: 95,
    matchPercentage: 95,
    matchedSkills: ['Git', 'Python', 'Adaptability'],
    missingSkills: [],
    recommendationMessage: 'You are a 95% match! All required foundational skills verified.',
    status: 'Selected',
    appliedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    notes: 'Enrolled to master automated CI/CD and container orchestration pipelines.',
    recruiterNotes: 'Congratulations! You have been accepted into the fully funded workshop cohort.',
  },
];

export const SAMPLE_RECRUITER_APPLICATIONS: Application[] = [
  SAMPLE_APPLICATIONS[0], // Alex Rivera (Shortlisted)
  {
    id: 'app-ind-cand-2',
    opportunityId: 'opp-ind-1',
    opportunity: SAMPLE_OPPORTUNITIES[0],
    studentId: 'student-priya-sharma',
    studentName: 'Priya Sharma',
    studentEmail: 'priya.sharma@iitb.ac.in',
    studentCollege: 'IIT Bombay',
    studentRoleReadiness: 94,
    recruiterId: 'demo-recruiter-id',
    matchScore: 96,
    matchPercentage: 96,
    matchedSkills: ['React', 'TypeScript', 'HTML/CSS', 'Git'],
    missingSkills: [],
    recommendationMessage: 'Top 2% candidate match with exceptional React and component architecture scores.',
    status: 'Interview',
    appliedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    notes: 'Worked on open-source web design system tools with 500+ GitHub stars.',
    recruiterNotes: 'System Architecture interview confirmed with VP of Engineering for Wednesday.',
    candidatePortfolio: {
      bio: 'Final year B.Tech Computer Science student at IIT Bombay. Core contributor to open-source UI libraries.',
      college: 'IIT Bombay',
      degree: 'B.Tech in Computer Science',
      graduationYear: '2026',
      cgpaOrPercentage: '9.4 / 10 CGPA',
      roleReadinessScore: 94,
      recommendedRole: 'Frontend Developer',
      assessedSkills: {
        'React': 100,
        'TypeScript': 95,
        'HTML/CSS': 95,
        'Git': 90,
        'Problem Solving': 95,
      },
      projects: [
        {
          title: 'NexusDesign System Core',
          description: 'Zero-runtime CSS-in-JS component library built on Radix UI primitives.',
          tech: ['TypeScript', 'React', 'Radix UI', 'Tailwind CSS'],
          githubUrl: 'https://github.com/priyasharma/nexus-design',
        },
      ],
      certifications: [
        {
          id: 'cert-priya-1',
          studentId: 'student-priya-sharma',
          title: 'Certified Cloud Native Associate (CKA)',
          issuer: 'Linux Foundation',
          issueDate: '2026-02-15',
          status: 'Verified',
        },
      ],
    },
  },
  {
    id: 'app-ind-cand-3',
    opportunityId: 'opp-ind-1',
    opportunity: SAMPLE_OPPORTUNITIES[0],
    studentId: 'student-rohan-gupta',
    studentName: 'Rohan Gupta',
    studentEmail: 'rohan.gupta@dtu.ac.in',
    studentCollege: 'Delhi Technological University (DTU)',
    studentRoleReadiness: 76,
    recruiterId: 'demo-recruiter-id',
    matchScore: 76,
    matchPercentage: 76,
    matchedSkills: ['HTML/CSS', 'React', 'Git'],
    missingSkills: ['TypeScript'],
    recommendationMessage: 'Good foundational match. TypeScript proficiency is recommended.',
    status: 'Applied',
    appliedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    notes: 'Developed campus event ticketing portal using React and Tailwind.',
    recruiterNotes: 'Application under review. Portfolio link verified.',
    candidatePortfolio: {
      bio: 'B.Tech Information Technology student at DTU. Passionate about modern web development and community tech.',
      college: 'Delhi Technological University (DTU)',
      degree: 'B.Tech in IT',
      graduationYear: '2026',
      cgpaOrPercentage: '8.2 / 10 CGPA',
      roleReadinessScore: 76,
      recommendedRole: 'Frontend Developer',
      assessedSkills: {
        'React': 75,
        'JavaScript': 80,
        'HTML/CSS': 85,
        'Git': 70,
        'Problem Solving': 70,
      },
      projects: [
        {
          title: 'DTU Fest Pass Portal',
          description: 'QR-code generation and pass validation system for annual technical symposium.',
          tech: ['React', 'Node.js', 'Express', 'MongoDB'],
        },
      ],
    },
  },
  {
    id: 'app-ind-cand-4',
    opportunityId: 'opp-ind-1',
    opportunity: SAMPLE_OPPORTUNITIES[0],
    studentId: 'student-ananya-das',
    studentName: 'Ananya Das',
    studentEmail: 'ananya.das@nitk.edu.in',
    studentCollege: 'NIT Surathkal',
    studentRoleReadiness: 70,
    recruiterId: 'demo-recruiter-id',
    matchScore: 68,
    matchPercentage: 68,
    matchedSkills: ['HTML/CSS', 'JavaScript'],
    missingSkills: ['React', 'TypeScript'],
    recommendationMessage: 'Promising frontend baseline, but lacks core production React experience.',
    status: 'Rejected',
    appliedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    notes: 'Interested in frontend web performance.',
    recruiterNotes: 'Skills gap in React hooks and state machines. Encouraged to reapply next quarter.',
    candidatePortfolio: {
      bio: 'Pre-final year Computer Engineering student at NIT Surathkal.',
      college: 'NIT Surathkal',
      degree: 'B.Tech Computer Engineering',
      graduationYear: '2027',
      cgpaOrPercentage: '7.9 / 10 CGPA',
      roleReadinessScore: 70,
      recommendedRole: 'Frontend Developer',
    },
  },
];

export const SAMPLE_CERTIFICATIONS: Certification[] = [
  {
    id: 'cert-1',
    studentId: 'demo-student-id',
    title: 'Modern React Architecture & Component Design',
    issuer: 'Apex Institute of Technology — Department of CS',
    issueDate: '2026-05-20',
    credentialUrl: 'https://credentials.apex.edu/verify/CS-REACT-8821',
    status: 'Verified',
    verifiedAt: '2026-05-22T10:00:00Z',
  },
  {
    id: 'cert-2',
    studentId: 'demo-student-id',
    title: 'Relational Database Design & SQL Optimization',
    issuer: 'Oracle Academy / University Partner Cell',
    issueDate: '2026-03-15',
    credentialUrl: 'https://verify.oracle.com/cert/DB-99014',
    status: 'Verified',
    verifiedAt: '2026-03-18T14:30:00Z',
  },
  {
    id: 'cert-3',
    studentId: 'demo-student-id',
    title: 'Docker Containerization & Kubernetes Fundamentals',
    issuer: 'Cloud Native Computing Foundation (CNCF)',
    issueDate: '2026-08-10',
    credentialUrl: 'https://cncf.io/verify/CKA-DOCKER-1102',
    status: 'Pending',
  },
];

export const SAMPLE_PROJECTS: StudentProject[] = [
  {
    id: 'proj-1',
    studentId: 'demo-student-id',
    title: 'CampusPlacement Cloud Portal',
    description: 'Full-stack reactive placement matching dashboard with role readiness calculations, real-time status tracking, and Supabase RLS policies.',
    technologies: ['React', 'TypeScript', 'Tailwind CSS', 'Supabase', 'Node.js'],
    projectUrl: 'https://campusplacement.preview.io',
    githubUrl: 'https://github.com/alexrivera/campus-placement-portal',
    status: 'Verified',
    verifiedBy: 'Dr. Devraj Patel (Dean)',
    verifiedAt: '2026-06-10T14:30:00Z',
    adminNotes: 'Institutional capstone project verified with distinction. Exceptional component architecture.',
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'proj-2',
    studentId: 'demo-student-id',
    title: 'Algorithmic Trading Dashboard',
    description: 'Sub-millisecond WebSocket chart visualizer with technical indicators (RSI, MACD) and custom canvas rendering.',
    technologies: ['JavaScript', 'HTML5 Canvas', 'Node.js', 'WebSocket', 'Tailwind'],
    projectUrl: 'https://algotrader-view.demo.app',
    githubUrl: 'https://github.com/alexrivera/algo-charting',
    status: 'Verified',
    verifiedBy: 'Dr. Devraj Patel (Dean)',
    verifiedAt: '2026-07-22T09:15:00Z',
    adminNotes: 'High performance rendering verified. Code passes campus open-source quality checks.',
    createdAt: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'proj-3',
    studentId: 'demo-student-id',
    title: 'Distributed Distributed Ledger Microservice',
    description: 'High-throughput idempotency ledger with Redis caching and PostgreSQL ACID transactional safety for fintech payment pipelines.',
    technologies: ['Python', 'PostgreSQL', 'Docker', 'Redis'],
    projectUrl: '',
    githubUrl: 'https://github.com/alexrivera/ledger-service',
    status: 'Pending',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const SAMPLE_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach-1',
    studentId: 'demo-student-id',
    title: '1st Place — National Smart Campus Hackathon 2026',
    description: 'Built a peer-to-peer textbook and skill exchange platform used by 4,000+ students.',
    date: '2026-04-12',
    issuer: 'Ministry of Education & Apex Institute',
  },
  {
    id: 'ach-2',
    studentId: 'demo-student-id',
    title: "Dean's Academic Merit Honor Roll",
    description: 'Awarded to top 5% academic performers across Computer Science and Engineering batches.',
    date: '2026-01-20',
    issuer: 'Apex Institute of Technology',
  },
];

export const SAMPLE_STUDENT_PORTFOLIO: StudentPortfolio = {
  studentId: 'demo-student-id',
  name: 'Alex Rivera',
  email: 'alex.rivera@apex.edu',
  college: 'Apex Institute of Technology',
  branch: 'Computer Science & Engineering',
  graduationYear: '2026',
  bio: 'Junior majoring in Computer Science with a focus on web application performance, TypeScript design systems, and responsive UX architectures.',
  targetRole: 'Full-Stack Cloud Engineer',
  resumeUrl: 'https://alexrivera.dev/resume.pdf',
  roleReadinessScore: 88,
  completionPercentage: 92,
  recommendedRole: 'Frontend Developer',
  assessedSkills: {
    'React': 80,
    'JavaScript': 80,
    'HTML/CSS': 80,
    'Git': 60,
    'SQL': 60,
    'Python': 40,
    'Communication': 80,
    'Teamwork': 80,
    'Problem Solving': 80,
    'Adaptability': 80,
  },
  projects: SAMPLE_PROJECTS,
  certifications: SAMPLE_CERTIFICATIONS,
  achievements: SAMPLE_ACHIEVEMENTS,
  internships: [
    {
      id: 'app-ind-1',
      title: 'Frontend React Engineering Intern',
      company: 'Nexus Cloud India',
      status: 'Shortlisted',
      appliedAt: '2026-09-08T00:00:00Z',
      duration: '6 Months',
    },
    {
      id: 'app-ind-4',
      title: 'Cloud Architecture & DevOps Workshop',
      company: 'Infosys Springboard',
      status: 'Selected',
      appliedAt: '2026-09-05T00:00:00Z',
      duration: '4 Weeks',
    },
  ],
};

export const SAMPLE_ADMIN_STUDENTS: AdminStudentSummary[] = [
  {
    id: 'demo-student-id',
    name: 'Alex Rivera',
    email: 'alex.rivera@apex.edu',
    college: 'Apex Institute of Technology',
    branch: 'Computer Science & Engineering',
    graduationYear: '2026',
    roleReadinessScore: 88,
    targetRole: 'Full-Stack Cloud Engineer',
    applicationsCount: 4,
    verifiedProjectsCount: 2,
    verifiedCertsCount: 2,
    placementStatus: 'In Process',
  },
  {
    id: 'student-priya-sharma',
    name: 'Priya Sharma',
    email: 'priya.sharma@apex.edu',
    college: 'Apex Institute of Technology',
    branch: 'Computer Science & Engineering',
    graduationYear: '2026',
    roleReadinessScore: 94,
    targetRole: 'Frontend Architect',
    applicationsCount: 3,
    verifiedProjectsCount: 1,
    verifiedCertsCount: 1,
    placementStatus: 'Placed',
  },
  {
    id: 'student-rohan-gupta',
    name: 'Rohan Gupta',
    email: 'rohan.gupta@apex.edu',
    college: 'Apex Institute of Technology',
    branch: 'Information Technology',
    graduationYear: '2026',
    roleReadinessScore: 76,
    targetRole: 'Full-Stack Developer',
    applicationsCount: 2,
    verifiedProjectsCount: 0,
    verifiedCertsCount: 1,
    placementStatus: 'Seeking',
  },
  {
    id: 'student-ananya-das',
    name: 'Ananya Das',
    email: 'ananya.das@apex.edu',
    college: 'Apex Institute of Technology',
    branch: 'Electronics & Communication',
    graduationYear: '2027',
    roleReadinessScore: 70,
    targetRole: 'Embedded Software Engineer',
    applicationsCount: 2,
    verifiedProjectsCount: 1,
    verifiedCertsCount: 0,
    placementStatus: 'Seeking',
  },
  {
    id: 'student-kabir-mehta',
    name: 'Kabir Mehta',
    email: 'kabir.mehta@apex.edu',
    college: 'Apex Institute of Technology',
    branch: 'Artificial Intelligence & Data Science',
    graduationYear: '2026',
    roleReadinessScore: 85,
    targetRole: 'Data & ML Engineer',
    applicationsCount: 5,
    verifiedProjectsCount: 2,
    verifiedCertsCount: 1,
    placementStatus: 'In Process',
  },
  {
    id: 'student-tanvi-verma',
    name: 'Tanvi Verma',
    email: 'tanvi.verma@apex.edu',
    college: 'Apex Institute of Technology',
    branch: 'Computer Science & Engineering',
    graduationYear: '2026',
    roleReadinessScore: 91,
    targetRole: 'Backend Systems Engineer',
    applicationsCount: 4,
    verifiedProjectsCount: 2,
    verifiedCertsCount: 2,
    placementStatus: 'Placed',
  },
];

export const SAMPLE_ADMIN_VERIFICATIONS: AdminVerificationItem[] = [
  {
    id: 'proj-3',
    type: 'project',
    studentId: 'demo-student-id',
    studentName: 'Alex Rivera',
    studentCollege: 'Apex Institute of Technology',
    studentBranch: 'Computer Science & Engineering',
    title: 'Distributed Distributed Ledger Microservice',
    descriptionOrIssuer: 'High-throughput idempotency ledger with Redis caching and PostgreSQL ACID safety.',
    link: 'https://github.com/alexrivera/ledger-service',
    githubUrl: 'https://github.com/alexrivera/ledger-service',
    tech: ['Python', 'PostgreSQL', 'Docker', 'Redis'],
    status: 'Pending',
    submittedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    adminNotes: '',
  },
  {
    id: 'cert-3',
    type: 'certificate',
    studentId: 'demo-student-id',
    studentName: 'Alex Rivera',
    studentCollege: 'Apex Institute of Technology',
    studentBranch: 'Computer Science & Engineering',
    title: 'Docker Containerization & Kubernetes Fundamentals',
    descriptionOrIssuer: 'Cloud Native Computing Foundation (CNCF)',
    link: 'https://cncf.io/verify/CKA-DOCKER-1102',
    status: 'Pending',
    submittedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    adminNotes: '',
  },
  {
    id: 'proj-priya-1',
    type: 'project',
    studentId: 'student-priya-sharma',
    studentName: 'Priya Sharma',
    studentCollege: 'Apex Institute of Technology',
    studentBranch: 'Computer Science & Engineering',
    title: 'NexusDesign System Core Component Library',
    descriptionOrIssuer: 'Accessible UI component primitives with Radix UI and Tailwind CSS.',
    link: 'https://github.com/priyasharma/nexus-design',
    githubUrl: 'https://github.com/priyasharma/nexus-design',
    tech: ['TypeScript', 'React', 'Tailwind CSS'],
    status: 'Pending',
    submittedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    adminNotes: '',
  },
  {
    id: 'cert-rohan-1',
    type: 'certificate',
    studentId: 'student-rohan-gupta',
    studentName: 'Rohan Gupta',
    studentCollege: 'Apex Institute of Technology',
    studentBranch: 'Information Technology',
    title: 'AWS Certified Cloud Practitioner',
    descriptionOrIssuer: 'Amazon Web Services Training & Certification',
    link: 'https://aws.amazon.com/verification/CLF-00192',
    status: 'Pending',
    submittedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    adminNotes: '',
  },
  {
    id: 'proj-1',
    type: 'project',
    studentId: 'demo-student-id',
    studentName: 'Alex Rivera',
    studentCollege: 'Apex Institute of Technology',
    studentBranch: 'Computer Science & Engineering',
    title: 'CampusPlacement Cloud Portal',
    descriptionOrIssuer: 'Full-stack reactive placement matching dashboard with role readiness calculations.',
    link: 'https://campusplacement.preview.io',
    githubUrl: 'https://github.com/alexrivera/campus-placement-portal',
    tech: ['React', 'TypeScript', 'Tailwind', 'Supabase'],
    status: 'Verified',
    submittedAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    adminNotes: 'Institutional capstone project verified with distinction.',
  },
  {
    id: 'cert-1',
    type: 'certificate',
    studentId: 'demo-student-id',
    studentName: 'Alex Rivera',
    studentCollege: 'Apex Institute of Technology',
    studentBranch: 'Computer Science & Engineering',
    title: 'Modern React Architecture & Component Design',
    descriptionOrIssuer: 'Apex Institute of Technology — Department of CS',
    link: 'https://credentials.apex.edu/verify/CS-REACT-8821',
    status: 'Verified',
    submittedAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    adminNotes: 'Verified against department records.',
  }
];

export const SAMPLE_ADMIN_ANALYTICS: AdminAnalyticsData = {
  kpis: {
    totalStudents: 248,
    activeOpportunities: 18,
    totalApplications: 142,
    placementReadyStudents: 164,
    selectedCandidates: 72,
    averageRoleReadiness: 82,
  },
  skillGaps: [
    { skill: 'Docker & Kubernetes', studentCount: 104, percentage: 42, gapLevel: 'high' },
    { skill: 'SQL & Query Optimization', studentCount: 88, percentage: 35, gapLevel: 'high' },
    { skill: 'TypeScript Generics & Types', studentCount: 65, percentage: 26, gapLevel: 'medium' },
    { skill: 'System Design & Scalability', studentCount: 58, percentage: 23, gapLevel: 'medium' },
    { skill: 'Cloud Microservices (AWS)', studentCount: 44, percentage: 18, gapLevel: 'low' },
  ],
  inDemandSkills: [
    { skill: 'React & Front-End Design', demandCount: 16, demandScore: 96 },
    { skill: 'TypeScript & JavaScript', demandCount: 14, demandScore: 92 },
    { skill: 'Node.js & REST APIs', demandCount: 12, demandScore: 89 },
    { skill: 'PostgreSQL & Relational Data', demandCount: 11, demandScore: 86 },
    { skill: 'Git & Agile Teamwork', demandCount: 10, demandScore: 84 },
    { skill: 'Python & Data Analysis', demandCount: 8, demandScore: 80 },
  ],
  readinessDistribution: [
    { range: '<60% (Needs Foundation)', count: 24, percentage: 10 },
    { range: '60%–74% (Developing)', count: 60, percentage: 24 },
    { range: '75%–84% (Proficient)', count: 96, percentage: 39 },
    { range: '85%+ (Placement Ready)', count: 68, percentage: 27 },
  ],
  branchOutcomes: [
    { branch: 'Computer Science & Engineering', totalStudents: 110, placedCount: 46, placementRate: 88 },
    { branch: 'Information Technology', totalStudents: 56, placedCount: 16, placementRate: 78 },
    { branch: 'AI & Data Science', totalStudents: 42, placedCount: 12, placementRate: 84 },
    { branch: 'Electronics & Communication', totalStudents: 40, placedCount: 8, placementRate: 70 },
  ],
  applicationStatusBreakdown: {
    'Applied': 48,
    'Shortlisted': 38,
    'Interview': 24,
    'Selected': 22,
    'Rejected': 10,
  },
};