// Mock fallback data for SkillBridge frontend
// Ensures 100% resilience on static deployments (Vercel) or when backend is offline

export const DEMO_USERS = {
  student: {
    _id: '6aa042a80f34485d694344cf',
    name: 'Alex Rivera',
    email: 'student@skillbridge.edu',
    role: 'student',
    college: 'Institute of Advanced Technology',
    company: '',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  recruiter: {
    _id: '6aa042a80f34485d694344cb',
    name: 'Sarah Jenkins',
    email: 'recruiter@techcorp.com',
    role: 'recruiter',
    college: '',
    company: 'TechCorp Labs',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
  },
  admin: {
    _id: '6aa042a80f34485d694344ca',
    name: 'Prof. Robert Vance',
    email: 'admin@skillbridge.edu',
    role: 'admin',
    college: 'Institute of Advanced Technology',
    company: '',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
};

export const DEMO_PROFILE = {
  _id: 'prof_alex_rivera_01',
  user: '6aa042a80f34485d694344cf',
  name: 'Alex Rivera',
  email: 'student@skillbridge.edu',
  college: 'Institute of Advanced Technology',
  branch: 'Computer Science & Engineering',
  graduationYear: 2026,
  skills: ['React', 'JavaScript', 'HTML/CSS', 'Git', 'Tailwind CSS', 'Node.js'],
  interests: ['Frontend Engineering', 'Full Stack Architecture', 'Open Source'],
  bio: 'Enthusiastic final-year CSE undergraduate passionate about building scalable, accessible web applications and modern interactive experiences.',
  resumeUrl: 'https://skillbridge.example/resumes/alex-rivera-resume.pdf',
  roleReadiness: {
    frontend: {
      percentage: 85,
      strengths: ['React & State Management', 'Modern JavaScript (ES6+)', 'Git & Version Control'],
      gaps: ['TypeScript', 'Testing (Jest/Cypress)'],
      recommendation: 'You are 85% ready for Frontend Developer. Improve TypeScript and Testing.',
    },
    dataAnalyst: {
      percentage: 50,
      strengths: ['Problem Solving & Incident Response'],
      gaps: ['SQL & Data Aggregation', 'Data Cleaning & Python/Pandas'],
      recommendation: 'You are 50% ready for Data Analyst. Improve SQL and Python.',
    },
    backend: {
      percentage: 70,
      strengths: ['RESTful API Architecture', 'Node.js & Express Middleware'],
      gaps: ['Database Design & Indexing'],
      recommendation: 'You are 70% ready for Backend Developer. Improve Database Indexing.',
    },
  },
};

export const DEMO_CERTIFICATES = [
  {
    _id: 'cert_01',
    title: 'Meta Front-End Developer Professional Certificate',
    issuer: 'Coursera / Meta',
    issueDate: '2025-06-15',
    credentialUrl: 'https://coursera.org/verify/meta-frontend-alex',
    status: 'Verified',
    verifiedAt: '2025-06-20',
  },
  {
    _id: 'cert_02',
    title: 'AWS Certified Cloud Practitioner',
    issuer: 'Amazon Web Services',
    issueDate: '2025-11-10',
    credentialUrl: 'https://aws.amazon.com/verification/CP-9921',
    status: 'Verified',
    verifiedAt: '2025-11-15',
  },
];

export const DEMO_PROJECTS = [
  {
    _id: 'proj_01',
    title: 'DevCollab - Real-Time Code Collaboration Platform',
    description: 'A WebRTC and Socket.io powered collaborative markdown & code editor supporting synchronized cursors, syntax highlighting, and live voice rooms.',
    technologies: ['React', 'Node.js', 'Socket.io', 'Tailwind CSS'],
    liveUrl: 'https://devcollab.demo.app',
    githubUrl: 'https://github.com/alexrivera/devcollab',
    status: 'Verified',
  },
  {
    _id: 'proj_02',
    title: 'EcoTrack - Campus Carbon Footprint Analyzer',
    description: 'Data-driven sustainability analytics portal measuring energy consumption, water usage, and carbon offsets across 12 university faculty buildings.',
    technologies: ['React', 'Chart.js', 'Express', 'MongoDB'],
    liveUrl: 'https://ecotrack.demo.app',
    githubUrl: 'https://github.com/alexrivera/ecotrack',
    status: 'Pending',
  },
];

export const DEMO_OPPORTUNITIES = [
  {
    _id: 'opp_01',
    title: 'Frontend Engineering Intern',
    company: 'TechCorp Labs',
    type: 'Internship',
    location: 'Remote',
    stipendOrSalary: '₹35,000 / month',
    duration: '6 Months',
    deadline: '2026-10-15',
    description: 'Join our design systems engineering squad building next-generation web portals. You will craft reusable component libraries in React, integrate RESTful APIs, and participate in daily agile standups.',
    requiredSkills: ['React', 'JavaScript', 'Tailwind CSS', 'Git'],
    eligibility: 'Pre-final or final year B.Tech / MCA students. Strong grasp of modern JavaScript and component architecture.',
    status: 'active',
  },
  {
    _id: 'opp_02',
    title: 'Junior Backend Developer',
    company: 'CloudScale Systems',
    type: 'Job',
    location: 'Bangalore, India',
    stipendOrSalary: '₹12 - 15 LPA',
    duration: 'Full Time',
    deadline: '2026-10-10',
    description: 'Seeking a proactive Junior Backend Developer to assist in architecting high-throughput microservices, managing MongoDB cluster replication, and building secure RESTful authorization endpoints.',
    requiredSkills: ['Node.js', 'Express', 'MongoDB', 'REST APIs', 'Git'],
    eligibility: 'Graduating batch of 2025/2026. Prior internship or production project experience preferred.',
    status: 'active',
  },
  {
    _id: 'opp_03',
    title: 'Data Analyst Intern',
    company: 'TechCorp Labs',
    type: 'Internship',
    location: 'Hyderabad, India',
    stipendOrSalary: '₹30,000 / month',
    duration: '3 Months',
    deadline: '2026-09-30',
    description: 'Work alongside senior analysts to build executive dashboards, clean behavioral customer telemetry, and generate SQL queries on petabyte-scale data lakes.',
    requiredSkills: ['SQL', 'Python', 'Pandas', 'Statistics', 'Git'],
    eligibility: 'Open to B.Tech, M.Tech, and Data Science students with strong problem-solving skills.',
    status: 'active',
  },
  {
    _id: 'opp_04',
    title: 'Full Stack Associate Software Engineer',
    company: 'CloudScale Systems',
    type: 'Job',
    location: 'Pune, India',
    stipendOrSalary: '₹9 - 13 LPA',
    duration: 'Full Time',
    deadline: '2026-11-01',
    description: 'Develop full stack cloud solutions using React on the frontend and Node.js with MongoDB on the backend. Ideal for enthusiastic engineers who love shipping end-to-end features.',
    requiredSkills: ['React', 'Node.js', 'MongoDB', 'JavaScript', 'REST APIs'],
    eligibility: 'Min 7.0 CGPA, B.Tech / B.E. / M.Tech in CS, IT, or related fields.',
    status: 'active',
  },
];

export const DEMO_APPLICATIONS = [
  {
    _id: 'app_01',
    opportunity: DEMO_OPPORTUNITIES[0],
    matchScore: 100,
    matchedSkills: ['React', 'JavaScript', 'Tailwind CSS', 'Git'],
    missingSkills: [],
    recommendationMessage: 'Perfect Match! Your profile satisfies 100% of the role technical stack requirements.',
    status: 'Interview',
    appliedAt: '2026-09-02T10:00:00.000Z',
    notes: 'I have hands-on experience building React applications with Tailwind CSS and Git version control.',
    statusHistory: [
      { status: 'Applied', updatedAt: '2026-09-02T10:00:00.000Z', comment: 'Application submitted' },
      { status: 'Shortlisted', updatedAt: '2026-09-05T14:30:00.000Z', comment: 'Profile and match score meet criteria' },
      { status: 'Interview', updatedAt: '2026-09-07T11:00:00.000Z', comment: 'Technical interview scheduled for Friday 2 PM' },
    ],
  },
  {
    _id: 'app_02',
    opportunity: DEMO_OPPORTUNITIES[1],
    matchScore: 60,
    matchedSkills: ['Node.js', 'Git', 'REST APIs'],
    missingSkills: ['MongoDB', 'Express'],
    recommendationMessage: 'Moderate Match. Consider building projects using MongoDB and Express to strengthen readiness.',
    status: 'Applied',
    appliedAt: '2026-09-06T15:30:00.000Z',
    notes: 'Excited about backend engineering and expanding my Node.js skillset.',
    statusHistory: [
      { status: 'Applied', updatedAt: '2026-09-06T15:30:00.000Z', comment: 'Application submitted' },
    ],
  },
];

export const DEMO_ASSESSMENT_QUESTIONS = [
  {
    id: 1,
    category: 'Technical',
    competency: 'React & State Management',
    roleAffinity: ['frontend'],
    question: 'In React, which hook is primarily used to perform side effects like data fetching or subscriptions?',
    options: ['useState', 'useEffect', 'useMemo', 'useReducer'],
  },
  {
    id: 2,
    category: 'Technical',
    competency: 'Modern JavaScript (ES6+)',
    roleAffinity: ['frontend', 'backend'],
    question: 'What is the primary difference between synchronous and asynchronous code execution in JavaScript?',
    options: [
      'Asynchronous code runs on a separate thread pool automatically managed by the browser hardware',
      'Asynchronous code does not block the main thread and relies on the Event Loop and Callback Queue',
      'Synchronous code can only execute inside async functions',
      'There is no difference; modern V8 engines execute everything concurrently',
    ],
  },
  {
    id: 3,
    category: 'Technical',
    competency: 'RESTful API Architecture',
    roleAffinity: ['backend'],
    question: 'Which HTTP method is considered idempotent and used in REST standards to replace an entire existing resource?',
    options: ['POST', 'PATCH', 'PUT', 'CONNECT'],
  },
  {
    id: 4,
    category: 'Technical',
    competency: 'Node.js & Express Middleware',
    roleAffinity: ['backend'],
    question: 'In an Express.js middleware function, what happens if neither res.send() nor next() is called?',
    options: [
      'The server immediately throws an UnhandledPromiseRejection error',
      'Express automatically returns HTTP 200 OK after 100 milliseconds',
      'The client request hangs indefinitely until a timeout occurs',
      'The request is restarted from the first middleware in the pipeline',
    ],
  },
  {
    id: 5,
    category: 'Technical',
    competency: 'Database Design & Indexing',
    roleAffinity: ['backend', 'dataAnalyst'],
    question: 'Why are database indexes (e.g., B-Tree indexes) applied to frequently queried columns?',
    options: [
      'They reduce disk space usage by compressing table records',
      'They speed up read query retrieval times at the cost of slight overhead on write operations',
      'They automatically encrypt sensitive user information at rest',
      'They guarantee zero null values can be stored in the table',
    ],
  },
  {
    id: 6,
    category: 'Technical',
    competency: 'SQL & Data Aggregation',
    roleAffinity: ['dataAnalyst'],
    question: 'In SQL, which clause filters rows AFTER aggregate functions (like SUM or COUNT) have been calculated?',
    options: ['WHERE', 'HAVING', 'ORDER BY', 'LIMIT'],
  },
  {
    id: 7,
    category: 'Technical',
    competency: 'Data Cleaning & Python/Pandas',
    roleAffinity: ['dataAnalyst'],
    question: 'In Python Pandas, what is the most idiomatic method to replace missing NaN values across a DataFrame column?',
    options: ['df[col].dropna()', 'df[col].fillna(value)', 'df[col].replace_null(value)', 'df[col].clean()'],
  },
  {
    id: 8,
    category: 'Professional',
    competency: 'Git & Version Control',
    roleAffinity: ['frontend', 'backend', 'dataAnalyst'],
    question: 'Which Git command is best suited for integrating commits from a feature branch into main while preserving linear history?',
    options: ['git reset --hard', 'git rebase main', 'git push --force', 'git checkout -b'],
  },
];

export const DEMO_ADMIN_ANALYTICS = {
  totalStudents: 148,
  placedStudents: 92,
  placementRate: 62.2,
  averageMatchRate: 78.4,
  totalOpportunities: 24,
  activeRecruiters: 12,
  pendingVerifications: 5,
  skillsDemandChart: [
    { skill: 'React', count: 18 },
    { skill: 'JavaScript', count: 22 },
    { skill: 'Node.js', count: 15 },
    { skill: 'Python', count: 14 },
    { skill: 'SQL', count: 16 },
    { skill: 'Git', count: 20 },
  ],
  roleReadinessAverage: {
    frontend: 74,
    backend: 68,
    dataAnalyst: 65,
  },
};

export const DEMO_ADMIN_VERIFICATIONS = [
  {
    _id: 'ver_01',
    type: 'Certificate',
    studentName: 'Alex Rivera',
    studentEmail: 'student@skillbridge.edu',
    title: 'Meta Front-End Developer Professional Certificate',
    issuer: 'Coursera / Meta',
    credentialUrl: 'https://coursera.org/verify/meta-frontend-alex',
    submittedAt: '2026-09-01T12:00:00.000Z',
    status: 'Pending',
  },
  {
    _id: 'ver_02',
    type: 'Project',
    studentName: 'Maya Patel',
    studentEmail: 'maya.patel@skillbridge.edu',
    title: 'EcoTrack - Campus Carbon Footprint Analyzer',
    issuer: 'Independent Research',
    credentialUrl: 'https://ecotrack.demo.app',
    submittedAt: '2026-09-03T09:30:00.000Z',
    status: 'Pending',
  },
];

export const DEMO_ADMIN_USERS = [
  {
    _id: 'user_01',
    name: 'Alex Rivera',
    email: 'student@skillbridge.edu',
    role: 'student',
    college: 'Institute of Advanced Technology',
    createdAt: '2026-08-15T10:00:00.000Z',
  },
  {
    _id: 'user_02',
    name: 'Maya Patel',
    email: 'maya.patel@skillbridge.edu',
    role: 'student',
    college: 'Institute of Advanced Technology',
    createdAt: '2026-08-18T14:20:00.000Z',
  },
  {
    _id: 'user_03',
    name: 'Sarah Jenkins',
    email: 'recruiter@techcorp.com',
    role: 'recruiter',
    company: 'TechCorp Labs',
    createdAt: '2026-08-10T08:45:00.000Z',
  },
  {
    _id: 'user_04',
    name: 'Prof. Robert Vance',
    email: 'admin@skillbridge.edu',
    role: 'admin',
    college: 'Institute of Advanced Technology',
    createdAt: '2026-08-01T09:00:00.000Z',
  },
];
